name: distrobox
type: app
base: core20
adopt-info: distrobox
summary: Use any Linux distribution inside your terminal
description: |
  Use any Linux distribution inside your terminal. Enable both backward and forward compatibility with software and freedom to use whatever distribution you’re more comfortable with. Distrobox uses podman or docker to create containers using the Linux distribution of your choice. The created container will be tightly integrated with the host, allowing sharing of the HOME directory of the user, external storage, external USB devices and graphical apps (X11/Wayland), and audio.
grade: stable
confinement: devmode

parts:
  distrobox:
    plugin: dump
    source: https://github.com/89luca89/distrobox.git
    source-type: git
    override-build: |
      snapcraftctl set-version $(git describe --always --tag)
      snapcraftctl build
      ./install
    stage-snaps:
      - docker

apps:
  distrobox:
    command: distrobox
    plugs:
      - desktop
